version: '3'
services:
  vaultwarden:
    image: vaultwarden/server
    container_name: bitwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=xxxxxx
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.bitwarden-ui-https.rule=Host(`bitwarden.devdoll.icu`)
      - traefik.http.routers.bitwarden-ui-https.tls=true
      - traefik.http.routers.bitwarden-ui-https.tls.certresolver=le
      - traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket-https.rule=Host(`bitwarden.devdoll.icu`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket-https.tls=true
      - traefik.http.routers.bitwarden-websocket-https.tls.certresolver=le
      - traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
networks:
  default:
    name: traefik_default
    external: true