version: '3'
services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dynamic_conf.toml:/etc/traefik/dynamic_conf.toml
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock