[http.routers.api]
  rule = "Host(`traefik.devdoll.art`)"
  service = "api@internal"
  middlewares = ["auth"]
  [http.routers.api.tls]
    certResolver = "le"

[http.routers.bt]
  rule = "Host(`bt.devdoll.art`)"
  service = "bt"
  [http.routers.bt.tls]
    certResolver = "le"

[http.routers.bt-not-secure]
  rule = "Host(`bt.devdoll.art`)"
  entrypoints = "web"
  service = "bt"
  middlewares = ["redirect-web-secure"]

[http.routers.bitwarden-ui-not-secure]
  rule = "Host(`bitwarden.devdoll.icu`)"
  entrypoints = "web"
  service = "bitwarden-ui@docker"
  middlewares = ["redirect-web-secure"]

[http.routers.bitwarden-websocket-not-secure]
  rule = "Host(`bitwarden.devdoll.icu`) && Path(`/notifications/hub`)"
  entrypoints = "web"
  service = "bitwarden-websocket@docker"
  middlewares = ["redirect-web-secure"]


[http.middlewares]
  [http.middlewares.auth.basicAuth]
    users = ["liangniang:$apr1$eeYKtNnF$plWflIpO95tdE1chPdiy51"]
  [http.middlewares.redirect-web-secure.redirectscheme]
    scheme = "https"
    permanent = true

[http.services]
  [http.services.bt.loadBalancer]
    [[http.services.bt.loadBalancer.servers]]
      url = "http://127.0.0.1:8888/"
