[http.routers.api]
  rule = "Host(`traefik.devdoll.art`)"
  service = "api@internal"
  middlewares = ["auth"]

  [http.routers.api.tls]
    certResolver = "le"


[http.middlewares.auth.basicAuth]
  users = [
    "liangniang:$apr1$eeYKtNnF$plWflIpO95tdE1chPdiy51",
  ]