version: '3'
services:
  http:
    image: hub.devdoll.icu/liangniang/euclid-web
    container_name: euclid-web
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.euclid-web.rule=Host(`euclid.${DOMAIN_NAME}`)
      - traefik.http.routers.euclid-web.service=euclid-web
      - traefik.http.services.euclid-web.loadbalancer.server.port=80
networks:
  default:
    name: traefik_default
    external: true